spring.application.name=movie-recommendation

spring.datasource.url=jdbc:mysql://localhost:3306/mrsdb
spring.datasource.username=root
spring.datasource.password=shivam9500@

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
