spring.application.name=movie-recommendation

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mrsdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:shivam9500@}
server.port=${PORT:8080}

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
